[package]
name = "leptos-forms-rs"
version = "0.1.0"
edition = "2021"
description = "Type-safe, reactive form handling library for Leptos applications"
license = "MIT"
repository = "https://github.com/your-org/leptos-forms-rs"
keywords = ["leptos", "forms", "validation", "web", "wasm"]
categories = ["web-programming", "wasm"]

[dependencies]
# Leptos version compatibility
leptos_06 = { package = "leptos", version = "0.6", optional = true, features = ["csr"] }
leptos_08 = { package = "leptos", version = "0.8", optional = true, features = ["csr"] }

# Common dependencies
serde = { workspace = true }
serde_json = { workspace = true }
leptos-forms-rs-macro = { path = "../leptos-forms-rs-macro" }
web-sys = { version = "0.3", features = ["Window", "Storage"] }
wasm-bindgen = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
gloo-net = { workspace = true }
gloo-timers = { workspace = true }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
log = { workspace = true }
lazy_static = { workspace = true }

[features]
default = ["leptos-0-6", "csr"]
leptos-0-6 = ["leptos_06"]
leptos-0-8 = ["leptos_08"]

# Leptos 0.6 features
csr = ["leptos-0-6", "leptos_06/csr"]
ssr = ["leptos-0-6", "leptos_06/ssr"]
hydrate = ["leptos-0-6", "leptos_06/hydrate"]

# Leptos 0.8 features
csr-08 = ["leptos-0-8", "leptos_08/csr"]
ssr-08 = ["leptos-0-8", "leptos_08/ssr"]
hydrate-08 = ["leptos-0-8", "leptos_08/hydrate"]

[lib]
name = "leptos_forms_rs"
path = "src/lib.rs"
