name: WASM Tests (Legacy)

on:
  workflow_dispatch: # Only run manually if needed

jobs:
  wasm-test:
    name: WASM Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Show tool versions
        run: |
          rustc --version
          cargo --version
          wasm-pack --version
          google-chrome --version || true
          firefox --version || true

      - name: Build workspace
        run: cargo build --workspace --all-targets

      - name: Run Rust tests
        run: cargo test --workspace

      - name: Run WASM tests (Node)
        working-directory: tests
        run: wasm-pack test --node

      - name: Run WASM tests (Headless Chrome)
        working-directory: tests
        env:
          CHROME: google-chrome
        run: wasm-pack test --headless --chrome

      - name: Run WASM tests (Headless Firefox)
        working-directory: tests
        run: wasm-pack test --headless --firefox
